--- 
- 
  delay: 2
  get_url: 
    dest: /tmp
    url: "https://www.rfxn.com/downloads/maldetect-current.tar.gz"
  name: "Get maldet installer archive"
  register: __maldet_download
  retries: 5
  until: "__maldet_download is succeeded"
- 
  name: "Unarchive maldet installer"
  unarchive: 
    dest: /tmp
    remote_src: true
    src: /tmp/maldetect-current.tar.gz
- 
  args: 
    chdir: "/tmp/maldetect-{{ maldet_version }}"
    creates: /usr/local/sbin/maldet
  command: "bash install.sh"
  name: "Installing maldet"
- 
  name: "Configuring maldet"
  template: 
    dest: /usr/local/maldetect/conf.maldet
    src: maldet_conf.maldet.j2
- 
  name: "Ensure epel repo present"
  yum: 
    name: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm"
    state: present
- 
  name: "Install the latest version of Glibc"
  yum: 
    name: glibc.i686
    state: latest
- 
  name: "Install inotify"
  yum: 
    name: inotify-tools
    state: latest
- 
  name: "Start and enable maldet service"
  service: 
    enabled: true
    name: maldet
    state: started
  when: 
    - maldet_service_enabled|bool
    - "maldet_default_monitor_mode is defined and maldet_default_monitor_mode"
- 
  name: "run maldet in monitor mode"
  replace: 
    path: /etc/sysconfig/maldet
    regexp: "#MONITOR_MODE=\"users\""
    replace: MONITOR_MODE="users"
- 
  name: "Restart service maldet"
  service: 
    name: maldet
    state: restarted                                                                                                  1,3           Top
                                                                                                              
