---
- name: Get maldet installer archive
  get_url:
    url: https://www.rfxn.com/downloads/maldetect-current.tar.gz
    dest: /tmp
  register: __maldet_download
  until: __maldet_download is succeeded
  retries: 5
  delay: 2

- name: Unarchive maldet installer
  unarchive:
    src: /tmp/maldetect-current.tar.gz
    dest: /tmp
    remote_src: true

- name: Installing maldet
  command: bash install.sh
  args:
    chdir: "/tmp/maldetect-1.6.4"
    creates: /usr/local/sbin/maldet

- name: Configuring maldet
  template:
    src: maldet_conf.maldet.j2
    dest: /usr/local/maldetect/conf.maldet
#  notify: restart maldet
- name: Ensure epel repo present
  yum:
    name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
    state: present
- name: Install the latest version of Glibc
  yum:
    name: glibc.i686
    state: latest
- name: Install inotify
  yum:
    name: inotify-tools
    state: latest

- name: Start and enable maldet service
  service:
    name: maldet
    state: started
    enabled: true
  when:
    - maldet_service_enabled|bool
    - maldet_default_monitor_mode is defined and maldet_default_monitor_mode
- name:  run maldet in monitor mode
  replace:
      path: /etc/sysconfig/maldet
      regexp: '#MONITOR_MODE="users"'
      replace: 'MONITOR_MODE="users"'
- name: Restart service maldet
  service:
    name: maldet
    state: restarted
